# = const(1) # Keyboard Error Roll Over
# = const(2) # Keyboard POST Fail
# = const(3) # Keyboard Error Undefined
_A = const(4) # Keyboard a and A
_B = const(5) # Keyboard b and B
_C = const(6) # Keyboard c and C
_D = const(7) # Keyboard d and D
_E = const(8) # Keyboard e and E
_F = const(9) # Keyboard f and F
_G = const(10) # Keyboard g and G
_H = const(11) # Keyboard h and H
_I = const(12) # Keyboard i and I
_J = const(13) # Keyboard j and J
_K = const(14) # Keyboard k and K
_L = const(15) # Keyboard l and L
_M = const(16) # Keyboard m and M
_N = const(17) # Keyboard n and N
_O = const(18) # Keyboard o and O
_P = const(19) # Keyboard p and P
_Q = const(20) # Keyboard q and Q
_R = const(21) # Keyboard r and R
_S = const(22) # Keyboard s and S
_T = const(23) # Keyboard t and T
_U = const(24) # Keyboard u and U
_V = const(25) # Keyboard v and V
_W = const(26) # Keyboard w and W
_X = const(27) # Keyboard x and X
_Y = const(28) # Keyboard y and Y
_Z = const(29) # Keyboard z and Z
_1 = const(30) # Keyboard 1 and !
_2 = const(31) # Keyboard 2 and @
_3 = const(32) # Keyboard 3 and #
_4 = const(33) # Keyboard 4 and $
_5 = const(34) # Keyboard 5 and %
_6 = const(35) # Keyboard 6 and ^
_7 = const(36) # Keyboard 7 and &
_8 = const(37) # Keyboard 8 and *
_9 = const(38) # Keyboard 9 and (
_0 = const(39) # Keyboard 0 and )
_RETURN = const(40) # Keyboard Return (ENTER)
_ESC = const(41) # Keyboard ESCAPE
_BSP = const(42) # Keyboard DELETE (Backspace)
_TAB = const(43) # Keyboard Tab
_SPACE = const(44) # Keyboard Spacebar
_MINUS = const(45) # Keyboard - and _
_EQ = const(46) # Keyboard = and +
_LB = const(47) # Keyboard [ and {
_RB = const(48) # Keyboard ] and }
_BACKSLASH = const(49) # Keyboard \ and |
_SEMICOLON = const(51) # Keyboard ; and :
_APOSTROPHE = const(52) # Keyboard ' and "
_GRAVE = const(53) # Keyboard ` and ~
_COMMA = const(54) # Keyboard , and <
_PERIOD = const(55) # Keyboard . and >
_SLASH = const(56) # Keyboard / and ?
_CAPS_LOCK = const(57) # Keyboard Caps Lock
_F1 = const(58) # Keyboard F1
_F2 = const(59) # Keyboard F2
_F3 = const(60) # Keyboard F3
_F4 = const(61) # Keyboard F4
_F5 = const(62) # Keyboard F5
_F6 = const(63) # Keyboard F6
_F7 = const(64) # Keyboard F7
_F8 = const(65) # Keyboard F8
_F9 = const(66) # Keyboard F9
_F10 = const(67) # Keyboard F10
_F11 = const(68) # Keyboard F11
_F12 = const(69) # Keyboard F12
_PS = const(70) # Keyboard Print Screen
_SCL = const(71) # Keyboard Scroll Lock
_BREAK = const(72) # Keyboard Pause
_INSERT = const(73) # Keyboard Insert
_PS = const(70) # Print screen
_SCL = const(71) # Scroll lock
_PA = const(72) # Pause
_INS = const(73) # Insert
_HOME = const(74) # Home
_PGUP = const(75) # Page up
_DEL = const(76) # Delete
_END = const(77) # End
_PGDN = const(78) # Page down
_AR = const(79) # Arrow right
_AL = const(80) # Arrow left
_AD = const(81) # Arrow down
_AU = const(82) # Arrow up

_NML = const(83) # Keyboard Num Lock and Clear
_KP_DIVIDE = const(84) # Keypad /
_KP_MULTIPLY = const(85) # Keypad *
_KP_SUBTRACT = const(86) # Keypad -
_KP_ADD = const(87) # Keypad +
_KP_ENTER = const(88) # Keypad ENTER
_KP_1 = const(89) # Keypad 1 and End
_KP_2 = const(90) # Keypad 2 and Down Arrow
_KP_3 = const(91) # Keypad 3 and PageDn
_KP_4 = const(92) # Keypad 4 and Left Arrow
_KP_5 = const(93) # Keypad 5
_KP_6 = const(94) # Keypad 6 and Right Arrow
_KP_7 = const(95) # Keypad 7 and Home
_KP_8 = const(96) # Keypad 8 and Up Arrow
_KP_9 = const(97) # Keypad 9 and Page Up
_KP_0 = const(98) # Keypad 0 and Insert
_KP_DOT = const(99) # Keypad . and Delete
_BSL = const(100) # Keyboard Non-US \ and |

_APP = const(101) # Menu

_POW = const(102) # Keyboard Power
_KP_EQ = const(103) # Keypad =
_F13 = const(104) # Keyboard F13
_F14 = const(105) # Keyboard F14
_F15 = const(106) # Keyboard F15
_F16 = const(107) # Keyboard F16
_F17 = const(108) # Keyboard F17
_F18 = const(109) # Keyboard F18
_F19 = const(110) # Keyboard F19
_F20 = const(111) # Keyboard F20
_F21 = const(112) # Keyboard F21
_F22 = const(113) # Keyboard F22
_F23 = const(114) # Keyboard F23
_F24 = const(115) # Keyboard F24
# = const(116) # Keyboard Execute
# = const(117) # Keyboard Help
# = const(118) # Keyboard Menu
# = const(119) # Keyboard Select
_MEDIA_STOP = const(120) # Keyboard Stop
# = const(121) # Keyboard Again
# = const(122) # Keyboard Undo
# = const(123) # Keyboard Cut
# = const(124) # Keyboard Copy
# = const(125) # Keyboard Paste
# = const(126) # Keyboard Find
_VOLUME_MUTE = const(127) # Keyboard Mute
_VOLUME_UP = const(128) # Keyboard Volume Up
_VOLUME_DOWN = const(129) # Keyboard Volume Down
# = const(130) # Keyboard Locking Caps Lock
# = const(131) # Keyboard Locking Num Lock
# = const(132) # Keyboard Locking Scroll Lock
_KP_COMMA = const(133) # Keypad Comma
# = const(134) # Keypad Equal Sign
# = const(135) # Keyboard International1
# = const(136) # Keyboard International2
# = const(137) # Keyboard International3
# = const(138) # Keyboard International4
# = const(139) # Keyboard International5
# = const(140) # Keyboard International6
# = const(141) # Keyboard International7
# = const(142) # Keyboard International8
# = const(143) # Keyboard International9
# = const(144) # Keyboard LANG1
# = const(145) # Keyboard LANG2
# = const(146) # Keyboard LANG3
# = const(147) # Keyboard LANG4
# = const(148) # Keyboard LANG5
# = const(149) # Keyboard LANG6
# = const(150) # Keyboard LANG7
# = const(151) # Keyboard LANG8
# = const(152) # Keyboard LANG9
# = const(153) # Keyboard Alternate Erase
# = const(154) # Keyboard SysReq/Attention
# = const(155) # Keyboard Cancel
# = const(156) # Keyboard Clear
# = const(157) # Keyboard Prior
# = const(158) # Keyboard Return
# = const(159) # Keyboard Separator
# = const(160) # Keyboard Out
# = const(161) # Keyboard Oper
# = const(162) # Keyboard Clear/Again
# = const(163) # Keyboard CrSel/Props
# = const(164) # Keyboard ExSel
# = const(176) # Keypad 00
# = const(177) # Keypad 000
# = const(178) # Thousands Separator
# = const(179) # Decimal Separator
# = const(180) # Currency Unit
# = const(181) # Currency Sub-unit
_KPLP = const(182) # Keypad (
_KPRP = const(183) # Keypad )
_KPLSB = const(184) # Keypad {
_KPRSB = const(185) # Keypad }
# = const(186) # Keypad Tab
# = const(187) # Keypad Backspace
# = const(188) # Keypad A
# = const(189) # Keypad B
# = const(190) # Keypad C
# = const(191) # Keypad D
# = const(192) # Keypad E
# = const(193) # Keypad F
# = const(194) # Keypad XOR
# = const(195) # Keypad ^
# = const(196) # Keypad %
_KPLT = const(197) # Keypad <
_KPGT = const(198) # Keypad >
# = const(199) # Keypad &
# = const(200) # Keypad &&
_PIPE = const(201) # Keypad |
# = const(202) # Keypad ||
_CL = const(203) # Keypad :
# = const(204) # Keypad #
_AT = const(205) # Keypad Space
# = const(206) # Keypad @
_BANG = const(207) # Keypad !
# = const(208) # Keypad Memory Store
# = const(209) # Keypad Memory Recall
# = const(210) # Keypad Memory Clear
# = const(211) # Keypad Memory Add
# = const(212) # Keypad Memory Subtract
# = const(213) # Keypad Memory Multiply
# = const(214) # Keypad Memory Divide
# = const(215) # Keypad +/-
# = const(216) # Keypad Clear
# = const(217) # Keypad Clear Entry
# = const(218) # Keypad Binary
# = const(219) # Keypad Octal
# = const(220) # Keypad Decimal
# = const(221) # Keypad Hexadecimal
KEY_PREVIOUSSONG = const(234) # Previous Song
KEY_NEXTSONG = const(235) # Next Song
KEY_EJECTCD = const(236) # Eject CD
KEY_VOLUMEUP = const(237) # Volume Up
KEY_VOLUMEDOWN = const(238) # Volume Down
KEY_MUTE = const(239) # Mute
KEY_WWW = const(240) # Browser
KEY_BACK = const(241) # Back
KEY_FORWARD = const(242) # Forward
KEY_STOP = const(243) # Stop
KEY_FIND = const(244) # Find
KEY_SCROLLUP = const(245) # Scroll Up
KEY_SCROLLDOWN = const(246) # Scroll Down
KEY_EDIT = const(247) # Edit
KEY_SLEEP = const(248) # Sleep
KEY_COFFEE = const(249) # Hybernate / Power On
KEY_REFRESH = const(250) # Refresh
KEY_CALC = const(251) # Calculator


_LCT = const(0x0100) # Left control
_LSH = const(0x0200) # Left shift
_LAL = const(0x0400) # Left alternate
_LSP = const(0x0800) # Left super
_RCT = const(0x1000) # Right control
_RSH = const(0x2000) # Right shift
_RAL = const(0x4000) # Right alternate
_RSP = const(0x8000) # Right super

_MT = const(-226) # Mute
_VU = const(-233) # Volume up
_VD = const(-234) # Volume down

_RR = const(-179) # Rewind
_FF = const(-180) # Fast forward
_NT = const(-181) # Next track
_PT = const(-182) # Prev track
_ST = const(-183) # Stop track
_PP = const(-205) # Play/pause

